<script setup lang="ts">
import { computed } from 'vue'
import { ArrowRight, Bike, Check, Clock3, Flag, Footprints, MapPin, Sparkles } from 'lucide-vue-next'
import type { CulturalPlace, Journey, TourRoute } from '../types'
const props = defineProps<{ route: TourRoute; stops: CulturalPlace[]; journey?: Journey; selectedPlaceId: string }>()
const emit = defineEmits<{ selectPlace: [id: string]; start: []; complete: [] }>()
const completedCount = computed(() => props.journey?.completedStopIds.length ?? 0)
const finished = computed(() => completedCount.value === props.stops.length && props.stops.length > 0)
const nextStop = computed(() => props.stops.find(place => !props.journey?.completedStopIds.includes(place.id)))
</script>

<template>
  <article class="route-detail">
    <div class="route-cover"><Bike v-if="route.scene === 'rickshaw'" :size="39" :stroke-width="1.3" /><Footprints v-else :size="39" :stroke-width="1.3" /><span>{{ route.tag }}</span><h2>{{ route.title }}</h2><p>{{ route.subtitle }}</p><div class="route-facts"><span><Clock3 :size="14" />{{ route.duration }} 分钟</span><span><MapPin :size="14" />{{ route.distance }}</span><span><Flag :size="14" />{{ stops.length }} 站</span></div></div>
    <p class="route-description">{{ route.description }}</p>
    <div v-if="journey" class="progress-card"><div><strong>{{ finished ? '这一程，已珍藏' : '您的游览进度' }}</strong><span>{{ completedCount }} / {{ stops.length }} 站</span></div><progress :value="completedCount" :max="stops.length" :aria-label="`已完成 ${completedCount} 个地点`" /><p>{{ finished ? '湖岸与街巷的故事，已留在您的足迹里。' : `接下来：${nextStop?.name}` }}</p></div>
    <div class="itinerary-heading"><h3>这一程，怎么走</h3><span>预设游览顺序</span></div>
    <ol class="itinerary"><li v-for="(stop, index) in stops" :key="stop.id" :class="{ selected: selectedPlaceId === stop.id, complete: journey?.completedStopIds.includes(stop.id) }"><button @click="emit('selectPlace', stop.id)"><span class="stop-number"><Check v-if="journey?.completedStopIds.includes(stop.id)" :size="14" /><template v-else>{{ String(index + 1).padStart(2, '0') }}</template></span><span class="stop-copy"><strong>{{ stop.name }}</strong><small>{{ stop.category }} · {{ stop.duration }} 分钟讲解</small></span><ArrowRight :size="14" /></button></li></ol>
    <div class="transport-note"><Bike :size="17" /><p>{{ route.transportNote }}</p></div>
    <p v-if="route.scene === 'rickshaw'" class="route-disclaimer">图上连线为游览示意，非实时导航。实际通行及停靠请听从现场安排。</p>
    <div class="journey-actions"><button v-if="!journey" class="primary-button" @click="emit('start')">{{ route.scene === 'rickshaw' ? '开启这段慢游' : '开始场馆探索' }}<ArrowRight :size="16" /></button><template v-else-if="!finished"><button v-if="selectedPlaceId === nextStop?.id" class="primary-button" @click="emit('complete')"><Check :size="16" />完成本站，前往下一站</button><button v-else class="primary-button" @click="emit('start')">继续游览 · {{ nextStop?.name }}<ArrowRight :size="16" /></button><small>体验模式 · 手动确认游览进度</small></template><div v-else class="finished-message"><Sparkles :size="19" /><span>已完成全部 {{ stops.length }} 站，去「我的足迹」回看</span></div></div>
  </article>
</template>

<style scoped>
.route-detail{padding:18px}.route-cover{background:var(--lake);color:white;border-radius:14px;padding:25px 19px 18px}.route-cover>svg{color:#cfdbc9;display:block;margin-bottom:20px}.route-cover>span{font-size:9px;padding:4px 7px;border:1px solid #ffffff45;border-radius:4px;color:#d1dfd6}.route-cover h2{font:600 23px/1.5 var(--display);margin:14px 0 5px}.route-cover>p{font-size:11px;color:#b9ccc4}.route-facts{display:flex;gap:12px;padding-top:19px;margin-top:20px;border-top:1px dashed #ffffff35;font-size:10px}.route-facts span{display:flex;align-items:center;gap:4px}.route-description{font-size:12px;line-height:1.9;color:var(--muted);margin:22px 0}.progress-card{padding:15px;background:#eaf0e7;border-radius:10px;font-size:11px;margin:20px 0}.progress-card>div{display:flex;justify-content:space-between}.progress-card progress{width:100%;height:5px;accent-color:var(--lake);margin-top:14px}.progress-card p{font-size:10px;color:var(--muted);margin:9px 0 0}.itinerary-heading{display:flex;align-items:center;justify-content:space-between}.itinerary-heading h3{font-size:12px}.itinerary-heading>span{font-size:10px;color:var(--muted)}.itinerary{padding:0;list-style:none;margin:12px 0}.itinerary li{position:relative;padding-bottom:12px}.itinerary li:not(:last-child)::after{content:'';position:absolute;top:39px;left:21px;height:calc(100% - 34px);border-left:1px dashed #bccbc0}.itinerary button{position:relative;display:flex;align-items:center;gap:13px;width:100%;border:1px solid transparent;background:none;padding:9px 8px;border-radius:10px;color:var(--ink);text-align:left;z-index:1}.itinerary .selected button{background:#edf2ed;border-color:#d6e0d6}.stop-number{display:grid;place-items:center;flex-shrink:0;width:26px;height:26px;border-radius:50%;background:#e7ede7;font:10px monospace;color:var(--lake)}.complete .stop-number{background:var(--lake);color:white}.stop-copy strong{font-size:12px;display:block}.stop-copy small{display:block;font-size:10px;color:var(--muted);margin-top:6px}.itinerary button>svg{margin-left:auto;color:#9ca99d}.transport-note{display:flex;gap:10px;align-items:flex-start;padding:14px;background:#f5f3e9;border-radius:10px;color:#8d7c50;margin-top:20px}.transport-note>svg{flex-shrink:0;margin-top:3px}.transport-note p{font-size:11px;line-height:1.8;margin:0}.route-disclaimer{font-size:10px;color:var(--muted);line-height:1.8}.journey-actions{margin-top:24px}.journey-actions small{display:block;text-align:center;font-size:10px;margin-top:10px;color:var(--muted)}.finished-message{display:flex;align-items:center;gap:10px;padding:16px;background:#e6eee3;border-radius:10px;color:var(--lake);font-size:12px;line-height:1.7}
</style>
