import type { TourLocale } from '@path-seeker/ts-shared'

const zh = {
  chooseLanguage: '选择讲解语言', routes: '选择这一程', routeHint: '跟随不同导游，听见不同的北京。', search: '搜索路线、导游或途经点', start: '开始行程', startHint: '开启定位，沿途为你讲解', back: '返回地图', end: '结束行程',
  play: '播放讲解', pause: '暂停', resume: '继续', content: '查看内容', close: '收起', next: '接下来看', complete: '完成这一站', locate: '开启近站讲解', stopLocate: '关闭定位', locationFailed: '定位不可用，仍可手动选择站点', loading: '正在加载…', retry: '重试',
  noRoutes: '暂无该语言的已发布路线', noNarration: '本站暂无该语言的讲解', voiceMissing: '设备未安装该语言语音，可继续阅读讲解', playbackFailed: '无法播放讲解，请重试或阅读正文', minutes: '分钟', stops: '站', finished: '行程已完成', ask: '问一问',
  routeUnavailable: '扫码路线不存在或尚未发布该语言版本，请重新选择', loadFailed: '加载失败，请重试', startFailed: '开始行程失败，请重试', saveFailed: '进度保存失败，请重试', video: '观看视频', guide: '导游', noMap: '地图服务尚未配置，仍可选择路线和播放讲解', changeLanguage: '切换语言',
  zoomIn: '放大地图', zoomOut: '缩小地图', overview: '路线全览', follow: '跟随视角', unfollow: '退出跟随',
  voiceAsk: '语音提问', voiceStop: '结束语音', voiceHint: '点一下，说话提问', voiceUnsupported: '当前浏览器不支持语音识别，已切换到文字提问',
}

export type TourMessages = Record<keyof typeof zh, string>

const messages: Record<TourLocale, TourMessages> = {
  zh,
  en: { chooseLanguage: 'Choose your language', routes: 'Choose your journey', routeHint: 'A different guide, a different side of Beijing.', search: 'Search routes, guides or stops', start: 'Start journey', startHint: 'Enable location for stories along the way', back: 'Back to map', end: 'End journey', play: 'Play narration', pause: 'Pause', resume: 'Resume', content: 'View story', close: 'Close', next: 'Up next', complete: 'Complete this stop', locate: 'Enable nearby stories', stopLocate: 'Stop location', locationFailed: 'Location unavailable. Select a stop manually.', loading: 'Loading…', retry: 'Retry', noRoutes: 'No published routes in this language', noNarration: 'No narration in this language for this stop', voiceMissing: 'This language voice is unavailable. You can read the story.', playbackFailed: 'Unable to play. Retry or read the story.', minutes: 'min', stops: 'stops', finished: 'Journey completed', ask: 'Ask', routeUnavailable: 'This route or language version is unavailable. Choose another route.', loadFailed: 'Unable to load. Please retry.', startFailed: 'Unable to start. Please retry.', saveFailed: 'Progress could not be saved. Please retry.', video: 'Watch video', guide: 'Guide', noMap: 'Map unavailable. You can select routes and play stories.', changeLanguage: 'Change language', zoomIn: 'Zoom in', zoomOut: 'Zoom out', overview: 'Route overview', follow: 'Follow view', unfollow: 'Stop following', voiceAsk: 'Ask by voice', voiceStop: 'Stop listening', voiceHint: 'Tap and speak', voiceUnsupported: 'Voice input is not supported in this browser; switched to typing.' },
  ru: { chooseLanguage: 'Выберите язык', routes: 'Выберите маршрут', routeHint: 'У каждого гида — свой Пекин.', search: 'Маршруты, гиды и остановки', start: 'Начать прогулку', startHint: 'Включите геолокацию для рассказов по пути', back: 'К карте', end: 'Завершить прогулку', play: 'Слушать рассказ', pause: 'Пауза', resume: 'Продолжить', content: 'Открыть рассказ', close: 'Закрыть', next: 'Далее', complete: 'Завершить остановку', locate: 'Рассказы поблизости', stopLocate: 'Отключить геолокацию', locationFailed: 'Геолокация недоступна. Выберите остановку вручную.', loading: 'Загрузка…', retry: 'Повторить', noRoutes: 'Нет опубликованных маршрутов на этом языке', noNarration: 'Нет рассказа на этом языке', voiceMissing: 'Голос для этого языка недоступен. Можно прочитать рассказ.', playbackFailed: 'Не удалось воспроизвести. Повторите или прочитайте рассказ.', minutes: 'мин', stops: 'остановок', finished: 'Прогулка завершена', ask: 'Спросить', routeUnavailable: 'Маршрут или языковая версия недоступны. Выберите другой маршрут.', loadFailed: 'Не удалось загрузить. Повторите.', startFailed: 'Не удалось начать. Повторите.', saveFailed: 'Не удалось сохранить. Повторите.', video: 'Смотреть видео', guide: 'Гид', noMap: 'Карта недоступна. Можно выбирать маршруты и слушать рассказы.', changeLanguage: 'Сменить язык', zoomIn: 'Приблизить', zoomOut: 'Отдалить', overview: 'Весь маршрут', follow: 'Режим слежения', unfollow: 'Выйти из слежения', voiceAsk: 'Спросить голосом', voiceStop: 'Остановить', voiceHint: 'Нажмите и говорите', voiceUnsupported: 'Голосовой ввод недоступен в этом браузере; переключено на текст.' },
  es: { chooseLanguage: 'Elige tu idioma', routes: 'Elige tu recorrido', routeHint: 'Cada guía cuenta un Pekín diferente.', search: 'Busca rutas, guías o paradas', start: 'Iniciar recorrido', startHint: 'Activa la ubicación para escuchar el recorrido', back: 'Volver al mapa', end: 'Finalizar recorrido', play: 'Escuchar relato', pause: 'Pausar', resume: 'Continuar', content: 'Ver relato', close: 'Cerrar', next: 'A continuación', complete: 'Completar esta parada', locate: 'Activar relatos cercanos', stopLocate: 'Desactivar ubicación', locationFailed: 'Ubicación no disponible. Selecciona una parada.', loading: 'Cargando…', retry: 'Reintentar', noRoutes: 'No hay rutas publicadas en este idioma', noNarration: 'No hay relato en este idioma para esta parada', voiceMissing: 'La voz de este idioma no está disponible. Puedes leer el relato.', playbackFailed: 'No se puede reproducir. Reintenta o lee el relato.', minutes: 'min', stops: 'paradas', finished: 'Recorrido completado', ask: 'Preguntar', routeUnavailable: 'La ruta o versión de idioma no está disponible. Elige otra ruta.', loadFailed: 'No se pudo cargar. Reintenta.', startFailed: 'No se pudo iniciar. Reintenta.', saveFailed: 'No se pudo guardar. Reintenta.', video: 'Ver vídeo', guide: 'Guía', noMap: 'Mapa no disponible. Puedes elegir rutas y escuchar relatos.', changeLanguage: 'Cambiar idioma', zoomIn: 'Acercar', zoomOut: 'Alejar', overview: 'Ver toda la ruta', follow: 'Vista de seguimiento', unfollow: 'Dejar de seguir', voiceAsk: 'Preguntar por voz', voiceStop: 'Detener', voiceHint: 'Toca y habla', voiceUnsupported: 'Este navegador no admite voz; cambiado a texto.' },
}

export function tourMessages(locale: TourLocale) { return messages[locale] }
