import type { TourLocale } from '@path-seeker/ts-shared'

const zh = {
  chooseLanguage: '选择讲解语言', routes: '选择这一程', routeHint: '跟随不同导游，听见不同的北京。', search: '搜索路线、导游或途经点', start: '开始行程', startHint: '开启定位，沿途为你讲解', back: '返回地图', end: '结束行程',
  play: '播放讲解', pause: '暂停', resume: '继续', content: '查看内容', close: '收起', next: '接下来看', complete: '完成这一站', locate: '开启近站讲解', stopLocate: '关闭定位', locationFailed: '定位不可用，仍可手动选择站点', loading: '正在加载…', retry: '重试',
  noRoutes: '暂无该语言的已发布路线', noNarration: '本站暂无该语言的讲解', voiceMissing: '设备未安装该语言语音，可继续阅读讲解', playbackFailed: '无法播放讲解，请重试或阅读正文', minutes: '分钟', stops: '站', finished: '行程已完成', ask: '问一问',
  routeUnavailable: '扫码路线不存在或尚未发布该语言版本，请重新选择', loadFailed: '加载失败，请重试', startFailed: '开始行程失败，请重试', saveFailed: '进度保存失败，请重试', video: '观看视频', guide: '导游', noMap: '地图服务尚未配置，仍可选择路线和播放讲解', changeLanguage: '切换语言',
  zoomIn: '放大地图', zoomOut: '缩小地图', overview: '路线全览', follow: '跟随视角', unfollow: '退出跟随',
  voiceAsk: '语音提问', voiceStop: '结束语音', voiceHint: '点一下，说话提问', voiceUnsupported: '当前浏览器不支持语音识别，已切换到文字提问',
  extraAudio: '额外音频', beforeAudio: '讲解前', afterAudio: '讲解后', skipExtraAudio: '跳过额外音频', replayStop: '重新播放整站', playingNow: '正在播放', approximateResume: '系统语音按句恢复，位置为近似', autoplayBlocked: '浏览器阻止了自动播放', continuePlayback: '继续播放', extraAudioFailed: '额外音频播放失败，已跳过：', locationUnknown: '定位精度不足，接近提示暂不可用，可手动选择站点', secondsShort: '秒',
  prevStop: '上一节点', nextStop: '下一节点', rewind15: '-15 秒', forward15: '+15 秒', enterStopPlay: '进入本节点播放', drawerNotPlaying: '正在播放其他节点：', browsingNoProgress: '浏览中，未切换行程进度', playbackProgress: '播放进度', seekAtStart: '已到本段开头', seekAtEnd: '已到本段末尾', nearbyAutoPlayHint: '走近下一站将自动播放', sequentialAutoHint: '定位不可用，播完自动进入下一站', voiceFellBack: '当前音色不可用，已使用默认音色',
}

/** v5 新增文案的各语言翻译；缺失时回落中文基线（见 tourMessages） */
const extraMessages: Partial<Record<TourLocale, Partial<Record<keyof typeof zh, string>>>> = {
  zh: {},
  en: { prevStop: 'Previous stop', nextStop: 'Next stop', rewind15: '-15 s', forward15: '+15 s', enterStopPlay: 'Play this stop', drawerNotPlaying: 'Playing another stop: ', browsingNoProgress: 'Browsing — journey progress unchanged', playbackProgress: 'Progress', seekAtStart: 'Start of this segment', seekAtEnd: 'End of this segment', nearbyAutoPlayHint: 'Playback starts automatically when you reach the next stop', sequentialAutoHint: 'Location unavailable — the next stop starts when this one finishes', voiceFellBack: 'This voice is unavailable; the default voice is used' },
  ru: { prevStop: 'Предыдущая остановка', nextStop: 'Следующая остановка', rewind15: '−15 с', forward15: '+15 с', enterStopPlay: 'Слушать эту остановку', drawerNotPlaying: 'Играет другая остановка: ', browsingNoProgress: 'Просмотр — прогресс маршрута не изменён', playbackProgress: 'Прогресс', seekAtStart: 'Начало фрагмента', seekAtEnd: 'Конец фрагмента', nearbyAutoPlayHint: 'Воспроизведение начнётся автоматически у следующей остановки', sequentialAutoHint: 'Геолокация недоступна — следующая остановка начнётся после этой', voiceFellBack: 'Этот голос недоступен, используется голос по умолчанию' },
  es: { prevStop: 'Parada anterior', nextStop: 'Parada siguiente', rewind15: '−15 s', forward15: '+15 s', enterStopPlay: 'Reproducir esta parada', drawerNotPlaying: 'Reproduciendo otra parada: ', browsingNoProgress: 'Explorando: progreso del recorrido sin cambios', playbackProgress: 'Progreso', seekAtStart: 'Inicio del fragmento', seekAtEnd: 'Final del fragmento', nearbyAutoPlayHint: 'La reproducción empieza al llegar a la siguiente parada', sequentialAutoHint: 'Ubicación no disponible: la siguiente parada empieza al terminar esta', voiceFellBack: 'Esta voz no está disponible; se usa la voz predeterminada' },
  fr: { prevStop: 'Étape précédente', nextStop: 'Étape suivante', rewind15: '−15 s', forward15: '+15 s', enterStopPlay: 'Lire cette étape', drawerNotPlaying: 'Lecture d’une autre étape : ', browsingNoProgress: 'Exploration : progression du parcours inchangée', playbackProgress: 'Progression', seekAtStart: 'Début du passage', seekAtEnd: 'Fin du passage', nearbyAutoPlayHint: 'La lecture démarre automatiquement à l’étape suivante', sequentialAutoHint: 'Localisation indisponible : l’étape suivante démarre à la fin de celle-ci', voiceFellBack: 'Cette voix est indisponible ; la voix par défaut est utilisée' },
  ja: { prevStop: '前のスポット', nextStop: '次のスポット', rewind15: '−15 秒', forward15: '+15 秒', enterStopPlay: 'このスポットを再生', drawerNotPlaying: '別のスポットを再生中：', browsingNoProgress: '閲覧中：コースの進行状況は変わりません', playbackProgress: '再生位置', seekAtStart: '区間の先頭', seekAtEnd: '区間の末尾', nearbyAutoPlayHint: '次のスポットに近づくと自動再生します', sequentialAutoHint: '位置情報が使えないため、再生後に次のスポットへ進みます', voiceFellBack: 'この音声は利用できないため、既定の音声を使用します' },
}

const arrivalMessages = {
  zh: { nearbyStop: '附近站点', arrived: '已到达', approaching: '接近', enterStop: '进入该站', keepNarration: '继续当前', metresShort: '米', overlappingStops: '附近有多个景点' },
  en: { nearbyStop: 'Nearby stop', arrived: 'Arrived at', approaching: 'Approaching', enterStop: 'Enter this stop', keepNarration: 'Keep the current one', metresShort: 'm', overlappingStops: 'Several stops nearby' },
  ru: { nearbyStop: 'Остановка рядом', arrived: 'Вы прибыли:', approaching: 'Рядом:', enterStop: 'Перейти к остановке', keepNarration: 'Оставить текущую', metresShort: 'м', overlappingStops: 'Рядом несколько остановок' },
  es: { nearbyStop: 'Parada cercana', arrived: 'Has llegado a', approaching: 'Cerca de', enterStop: 'Entrar en esta parada', keepNarration: 'Seguir con la actual', metresShort: 'm', overlappingStops: 'Varias paradas cerca' },
  fr: { nearbyStop: 'Étape à proximité', arrived: 'Vous êtes arrivé à', approaching: 'À proximité de', enterStop: 'Entrer dans cette étape', keepNarration: 'Garder l’étape actuelle', metresShort: 'm', overlappingStops: 'Plusieurs étapes à proximité' },
  ja: { nearbyStop: '近くのスポット', arrived: '到着しました', approaching: 'まもなく', enterStop: 'このスポットへ', keepNarration: '今のスポットを続ける', metresShort: 'm', overlappingStops: '近くに複数のスポット' },
}

export type TourMessages = Record<keyof typeof zh | keyof typeof arrivalMessages.zh, string>

const messages: Record<TourLocale, Partial<Record<keyof typeof zh, string>>> = {
  zh,
  en: { chooseLanguage: 'Choose your language', routes: 'Choose your journey', routeHint: 'A different guide, a different side of Beijing.', search: 'Search routes, guides or stops', start: 'Start journey', startHint: 'Enable location for stories along the way', back: 'Back to map', end: 'End journey', play: 'Play narration', pause: 'Pause', resume: 'Resume', content: 'View story', close: 'Close', next: 'Up next', complete: 'Complete this stop', locate: 'Enable nearby stories', stopLocate: 'Stop location', locationFailed: 'Location unavailable. Select a stop manually.', loading: 'Loading…', retry: 'Retry', noRoutes: 'No published routes in this language', noNarration: 'No narration in this language for this stop', voiceMissing: 'This language voice is unavailable. You can read the story.', playbackFailed: 'Unable to play. Retry or read the story.', minutes: 'min', stops: 'stops', finished: 'Journey completed', ask: 'Ask', routeUnavailable: 'This route or language version is unavailable. Choose another route.', loadFailed: 'Unable to load. Please retry.', startFailed: 'Unable to start. Please retry.', saveFailed: 'Progress could not be saved. Please retry.', video: 'Watch video', guide: 'Guide', noMap: 'Map unavailable. You can select routes and play stories.', changeLanguage: 'Change language', zoomIn: 'Zoom in', zoomOut: 'Zoom out', overview: 'Route overview', follow: 'Follow view', unfollow: 'Stop following', voiceAsk: 'Ask by voice', voiceStop: 'Stop listening', voiceHint: 'Tap and speak', voiceUnsupported: 'Voice input is not supported in this browser; switched to typing.', extraAudio: 'Extra audio', beforeAudio: 'Before the story', afterAudio: 'After the story', skipExtraAudio: 'Skip extra audio', replayStop: 'Replay this stop', playingNow: 'Now playing', approximateResume: 'System voice resumes sentence by sentence, so the position is approximate', autoplayBlocked: 'The browser blocked autoplay', continuePlayback: 'Continue playing', extraAudioFailed: 'Extra audio failed and was skipped: ', locationUnknown: 'Location is not accurate enough, so nearby prompts are unavailable; you can still pick a stop manually', secondsShort: 's' },
  ru: { chooseLanguage: 'Выберите язык', routes: 'Выберите маршрут', routeHint: 'У каждого гида — свой Пекин.', search: 'Маршруты, гиды и остановки', start: 'Начать прогулку', startHint: 'Включите геолокацию для рассказов по пути', back: 'К карте', end: 'Завершить прогулку', play: 'Слушать рассказ', pause: 'Пауза', resume: 'Продолжить', content: 'Открыть рассказ', close: 'Закрыть', next: 'Далее', complete: 'Завершить остановку', locate: 'Рассказы поблизости', stopLocate: 'Отключить геолокацию', locationFailed: 'Геолокация недоступна. Выберите остановку вручную.', loading: 'Загрузка…', retry: 'Повторить', noRoutes: 'Нет опубликованных маршрутов на этом языке', noNarration: 'Нет рассказа на этом языке', voiceMissing: 'Голос для этого языка недоступен. Можно прочитать рассказ.', playbackFailed: 'Не удалось воспроизвести. Повторите или прочитайте рассказ.', minutes: 'мин', stops: 'остановок', finished: 'Прогулка завершена', ask: 'Спросить', routeUnavailable: 'Маршрут или языковая версия недоступны. Выберите другой маршрут.', loadFailed: 'Не удалось загрузить. Повторите.', startFailed: 'Не удалось начать. Повторите.', saveFailed: 'Не удалось сохранить. Повторите.', video: 'Смотреть видео', guide: 'Гид', noMap: 'Карта недоступна. Можно выбирать маршруты и слушать рассказы.', changeLanguage: 'Сменить язык', zoomIn: 'Приблизить', zoomOut: 'Отдалить', overview: 'Весь маршрут', follow: 'Режим слежения', unfollow: 'Выйти из слежения', voiceAsk: 'Спросить голосом', voiceStop: 'Остановить', voiceHint: 'Нажмите и говорите', voiceUnsupported: 'Голосовой ввод недоступен в этом браузере; переключено на текст.', extraAudio: 'Дополнительное аудио', beforeAudio: 'Перед рассказом', afterAudio: 'После рассказа', skipExtraAudio: 'Пропускать дополнительное аудио', replayStop: 'Повторить остановку', playingNow: 'Сейчас играет', approximateResume: 'Системный голос продолжает по предложениям, позиция приблизительная', autoplayBlocked: 'Браузер заблокировал автовоспроизведение', continuePlayback: 'Продолжить воспроизведение', extraAudioFailed: 'Дополнительное аудио не воспроизвелось и пропущено: ', locationUnknown: 'Точность геолокации недостаточна, подсказки о приближении недоступны; остановку можно выбрать вручную', secondsShort: 'с' },
  es: { chooseLanguage: 'Elige tu idioma', routes: 'Elige tu recorrido', routeHint: 'Cada guía cuenta un Pekín diferente.', search: 'Busca rutas, guías o paradas', start: 'Iniciar recorrido', startHint: 'Activa la ubicación para escuchar el recorrido', back: 'Volver al mapa', end: 'Finalizar recorrido', play: 'Escuchar relato', pause: 'Pausar', resume: 'Continuar', content: 'Ver relato', close: 'Cerrar', next: 'A continuación', complete: 'Completar esta parada', locate: 'Activar relatos cercanos', stopLocate: 'Desactivar ubicación', locationFailed: 'Ubicación no disponible. Selecciona una parada.', loading: 'Cargando…', retry: 'Reintentar', noRoutes: 'No hay rutas publicadas en este idioma', noNarration: 'No hay relato en este idioma para esta parada', voiceMissing: 'La voz de este idioma no está disponible. Puedes leer el relato.', playbackFailed: 'No se puede reproducir. Reintenta o lee el relato.', minutes: 'min', stops: 'paradas', finished: 'Recorrido completado', ask: 'Preguntar', routeUnavailable: 'La ruta o versión de idioma no está disponible. Elige otra ruta.', loadFailed: 'No se pudo cargar. Reintenta.', startFailed: 'No se pudo iniciar. Reintenta.', saveFailed: 'No se pudo guardar. Reintenta.', video: 'Ver vídeo', guide: 'Guía', noMap: 'Mapa no disponible. Puedes elegir rutas y escuchar relatos.', changeLanguage: 'Cambiar idioma', zoomIn: 'Acercar', zoomOut: 'Alejar', overview: 'Ver toda la ruta', follow: 'Vista de seguimiento', unfollow: 'Dejar de seguir', voiceAsk: 'Preguntar por voz', voiceStop: 'Detener', voiceHint: 'Toca y habla', voiceUnsupported: 'Este navegador no admite voz; cambiado a texto.', extraAudio: 'Audio adicional', beforeAudio: 'Antes del relato', afterAudio: 'Después del relato', skipExtraAudio: 'Omitir el audio adicional', replayStop: 'Repetir esta parada', playingNow: 'Reproduciendo', approximateResume: 'La voz del sistema se reanuda frase a frase, así que la posición es aproximada', autoplayBlocked: 'El navegador bloqueó la reproducción automática', continuePlayback: 'Continuar la reproducción', extraAudioFailed: 'El audio adicional falló y se omitió: ', locationUnknown: 'La ubicación no es lo bastante precisa, los avisos de cercanía no están disponibles; puedes elegir una parada manualmente', secondsShort: 's' },
  fr: {
    chooseLanguage: 'Choisissez votre langue', routes: 'Choisissez votre parcours', routeHint: 'Chaque guide vous fait découvrir un autre visage de Pékin.', search: 'Rechercher un parcours, un guide ou une étape', start: 'Commencer le parcours', startHint: 'Activez la localisation pour écouter les récits en chemin', back: 'Retour à la carte', end: 'Terminer le parcours',
    play: 'Écouter le récit', pause: 'Pause', resume: 'Reprendre', content: 'Lire le récit', close: 'Fermer', next: 'À suivre', complete: 'Terminer cette étape', locate: 'Activer les récits à proximité', stopLocate: 'Désactiver la localisation', locationFailed: 'Localisation indisponible. Sélectionnez une étape manuellement.', loading: 'Chargement…', retry: 'Réessayer',
    noRoutes: 'Aucun parcours publié dans cette langue', noNarration: 'Aucun récit dans cette langue pour cette étape', voiceMissing: 'La voix de cette langue est indisponible. Vous pouvez lire le récit.', playbackFailed: 'Lecture impossible. Réessayez ou lisez le récit.', minutes: 'min', stops: 'étapes', finished: 'Parcours terminé', ask: 'Poser une question',
    routeUnavailable: 'Ce parcours ou sa version linguistique est indisponible. Choisissez un autre parcours.', loadFailed: 'Chargement impossible. Réessayez.', startFailed: 'Impossible de commencer. Réessayez.', saveFailed: 'Impossible de sauvegarder votre progression. Réessayez.', video: 'Voir la vidéo', guide: 'Guide', noMap: 'Carte indisponible. Vous pouvez choisir un parcours et écouter les récits.', changeLanguage: 'Changer de langue',
    zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', overview: 'Vue du parcours', follow: 'Suivre ma position', unfollow: 'Arrêter le suivi', voiceAsk: 'Poser une question à voix haute', voiceStop: 'Arrêter l’écoute', voiceHint: 'Appuyez et parlez', voiceUnsupported: 'Ce navigateur ne permet pas la saisie vocale. Saisissez votre question au clavier.',
    extraAudio: 'Audio supplémentaire', beforeAudio: 'Avant le récit', afterAudio: 'Après le récit', skipExtraAudio: 'Ignorer l’audio supplémentaire', replayStop: 'Réécouter cette étape', playingNow: 'Lecture en cours', approximateResume: 'La voix système reprend phrase par phrase, la position est donc approximative', autoplayBlocked: 'Le navigateur a bloqué la lecture automatique', continuePlayback: 'Continuer la lecture', extraAudioFailed: 'L’audio supplémentaire a échoué et a été ignoré : ', locationUnknown: 'La localisation n’est pas assez précise, les alertes de proximité sont indisponibles ; vous pouvez choisir une étape manuellement', secondsShort: 's',
  },
  ja: {
    chooseLanguage: 'ガイドの言語を選択', routes: 'コースを選択', routeHint: 'ガイドとともに、北京のさまざまな魅力を発見しましょう。', search: 'コース、ガイド、スポットを検索', start: 'コースを開始', startHint: '位置情報を有効にすると、道中でガイドを聞けます', back: '地図に戻る', end: 'コースを終了',
    play: 'ガイドを再生', pause: '一時停止', resume: '再開', content: '解説を読む', close: '閉じる', next: '次のスポット', complete: 'このスポットを完了', locate: '近くのスポットのガイドを有効にする', stopLocate: '位置情報を無効にする', locationFailed: '位置情報を取得できません。スポットを手動で選択してください。', loading: '読み込み中…', retry: '再試行',
    noRoutes: 'この言語で公開されているコースはありません', noNarration: 'このスポットにはこの言語の解説がありません', voiceMissing: 'この言語の音声が利用できません。解説をお読みください。', playbackFailed: '再生できません。再試行するか、解説をお読みください。', minutes: '分', stops: 'スポット', finished: 'コースを完了しました', ask: '質問する',
    routeUnavailable: 'このコースまたは言語版は利用できません。別のコースを選択してください。', loadFailed: '読み込めませんでした。再試行してください。', startFailed: '開始できませんでした。再試行してください。', saveFailed: '進行状況を保存できませんでした。再試行してください。', video: '動画を見る', guide: 'ガイド', noMap: '地図が利用できません。コースの選択とガイドの再生は可能です。', changeLanguage: '言語を変更',
    zoomIn: '拡大', zoomOut: '縮小', overview: 'コース全体を表示', follow: '現在地を追跡', unfollow: '追跡を終了', voiceAsk: '音声で質問', voiceStop: '音声入力を終了', voiceHint: 'タップして話してください', voiceUnsupported: 'このブラウザーは音声入力に対応していません。文字で質問してください。',
    extraAudio: '追加音声', beforeAudio: '解説の前', afterAudio: '解説の後', skipExtraAudio: '追加音声をスキップ', replayStop: 'このスポットを最初から再生', playingNow: '再生中', approximateResume: 'システム音声は文単位で再開するため、位置はおおよそです', autoplayBlocked: 'ブラウザーが自動再生をブロックしました', continuePlayback: '再生を続ける', extraAudioFailed: '追加音声を再生できずスキップしました：', locationUnknown: '位置情報の精度が不足しているため、接近通知は利用できません。スポットは手動で選択できます', secondsShort: '秒',
  },
}

export function tourMessages(locale: TourLocale): TourMessages {
  return {
    // 中文基线保证任何语言都不会缺键（v5 新增文案见 extraMessages）
    ...zh,
    ...messages[locale],
    ...extraMessages[locale],
    ...arrivalMessages[locale],
  }
}
