import type { TourLocale } from '@path-seeker/ts-shared'

const zh = {
  chooseLanguage: '选择讲解语言', routes: '选择这一程', routeHint: '跟随不同导游，听见不同的北京。', search: '搜索路线、导游或途经点', start: '开始行程', startHint: '开启定位，沿途为你讲解', back: '返回地图', end: '结束行程',
  play: '播放讲解', pause: '暂停', resume: '继续', content: '查看内容', close: '收起', next: '接下来看', complete: '完成这一站', locate: '开启近站讲解', stopLocate: '关闭定位', locationFailed: '定位不可用，仍可手动选择站点', loading: '正在加载…', retry: '重试',
  noRoutes: '暂无该语言的已发布路线', noNarration: '本站暂无该语言的讲解', voiceMissing: '设备未安装该语言语音，可继续阅读讲解', playbackFailed: '无法播放讲解，请重试或阅读正文', minutes: '分钟', stops: '站', finished: '行程已完成', ask: '问一问',
  routeUnavailable: '扫码路线不存在或尚未发布该语言版本，请重新选择', loadFailed: '加载失败，请重试', startFailed: '开始行程失败，请重试', saveFailed: '进度保存失败，请重试', video: '观看视频', guide: '导游', noMap: '地图服务尚未配置，仍可选择路线和播放讲解', changeLanguage: '切换语言',
  zoomIn: '放大地图', zoomOut: '缩小地图', overview: '路线全览', follow: '跟随视角', unfollow: '退出跟随',
  voiceAsk: '语音提问', voiceStop: '结束语音', voiceHint: '点一下，说话提问', voiceUnsupported: '当前浏览器不支持语音识别，已切换到文字提问',
}

const arrivalMessages = {
  zh: { nearbyStop: '附近站点', switchNarration: '切换讲解', keepNarration: '继续当前讲解' },
  en: { nearbyStop: 'Nearby stop', switchNarration: 'Switch narration', keepNarration: 'Keep current narration' },
  ru: { nearbyStop: 'Остановка рядом', switchNarration: 'Переключить рассказ', keepNarration: 'Оставить текущий рассказ' },
  es: { nearbyStop: 'Parada cercana', switchNarration: 'Cambiar relato', keepNarration: 'Seguir con el relato actual' },
  fr: { nearbyStop: 'Étape à proximité', switchNarration: 'Changer de récit', keepNarration: 'Garder le récit actuel' },
  ja: { nearbyStop: '近くのスポット', switchNarration: 'ガイドを切り替える', keepNarration: '今のガイドを続ける' },
}

export type TourMessages = Record<keyof typeof zh | keyof typeof arrivalMessages.zh, string>

const messages: Record<TourLocale, Record<keyof typeof zh, string>> = {
  zh,
  en: { chooseLanguage: 'Choose your language', routes: 'Choose your journey', routeHint: 'A different guide, a different side of Beijing.', search: 'Search routes, guides or stops', start: 'Start journey', startHint: 'Enable location for stories along the way', back: 'Back to map', end: 'End journey', play: 'Play narration', pause: 'Pause', resume: 'Resume', content: 'View story', close: 'Close', next: 'Up next', complete: 'Complete this stop', locate: 'Enable nearby stories', stopLocate: 'Stop location', locationFailed: 'Location unavailable. Select a stop manually.', loading: 'Loading…', retry: 'Retry', noRoutes: 'No published routes in this language', noNarration: 'No narration in this language for this stop', voiceMissing: 'This language voice is unavailable. You can read the story.', playbackFailed: 'Unable to play. Retry or read the story.', minutes: 'min', stops: 'stops', finished: 'Journey completed', ask: 'Ask', routeUnavailable: 'This route or language version is unavailable. Choose another route.', loadFailed: 'Unable to load. Please retry.', startFailed: 'Unable to start. Please retry.', saveFailed: 'Progress could not be saved. Please retry.', video: 'Watch video', guide: 'Guide', noMap: 'Map unavailable. You can select routes and play stories.', changeLanguage: 'Change language', zoomIn: 'Zoom in', zoomOut: 'Zoom out', overview: 'Route overview', follow: 'Follow view', unfollow: 'Stop following', voiceAsk: 'Ask by voice', voiceStop: 'Stop listening', voiceHint: 'Tap and speak', voiceUnsupported: 'Voice input is not supported in this browser; switched to typing.' },
  ru: { chooseLanguage: 'Выберите язык', routes: 'Выберите маршрут', routeHint: 'У каждого гида — свой Пекин.', search: 'Маршруты, гиды и остановки', start: 'Начать прогулку', startHint: 'Включите геолокацию для рассказов по пути', back: 'К карте', end: 'Завершить прогулку', play: 'Слушать рассказ', pause: 'Пауза', resume: 'Продолжить', content: 'Открыть рассказ', close: 'Закрыть', next: 'Далее', complete: 'Завершить остановку', locate: 'Рассказы поблизости', stopLocate: 'Отключить геолокацию', locationFailed: 'Геолокация недоступна. Выберите остановку вручную.', loading: 'Загрузка…', retry: 'Повторить', noRoutes: 'Нет опубликованных маршрутов на этом языке', noNarration: 'Нет рассказа на этом языке', voiceMissing: 'Голос для этого языка недоступен. Можно прочитать рассказ.', playbackFailed: 'Не удалось воспроизвести. Повторите или прочитайте рассказ.', minutes: 'мин', stops: 'остановок', finished: 'Прогулка завершена', ask: 'Спросить', routeUnavailable: 'Маршрут или языковая версия недоступны. Выберите другой маршрут.', loadFailed: 'Не удалось загрузить. Повторите.', startFailed: 'Не удалось начать. Повторите.', saveFailed: 'Не удалось сохранить. Повторите.', video: 'Смотреть видео', guide: 'Гид', noMap: 'Карта недоступна. Можно выбирать маршруты и слушать рассказы.', changeLanguage: 'Сменить язык', zoomIn: 'Приблизить', zoomOut: 'Отдалить', overview: 'Весь маршрут', follow: 'Режим слежения', unfollow: 'Выйти из слежения', voiceAsk: 'Спросить голосом', voiceStop: 'Остановить', voiceHint: 'Нажмите и говорите', voiceUnsupported: 'Голосовой ввод недоступен в этом браузере; переключено на текст.' },
  es: { chooseLanguage: 'Elige tu idioma', routes: 'Elige tu recorrido', routeHint: 'Cada guía cuenta un Pekín diferente.', search: 'Busca rutas, guías o paradas', start: 'Iniciar recorrido', startHint: 'Activa la ubicación para escuchar el recorrido', back: 'Volver al mapa', end: 'Finalizar recorrido', play: 'Escuchar relato', pause: 'Pausar', resume: 'Continuar', content: 'Ver relato', close: 'Cerrar', next: 'A continuación', complete: 'Completar esta parada', locate: 'Activar relatos cercanos', stopLocate: 'Desactivar ubicación', locationFailed: 'Ubicación no disponible. Selecciona una parada.', loading: 'Cargando…', retry: 'Reintentar', noRoutes: 'No hay rutas publicadas en este idioma', noNarration: 'No hay relato en este idioma para esta parada', voiceMissing: 'La voz de este idioma no está disponible. Puedes leer el relato.', playbackFailed: 'No se puede reproducir. Reintenta o lee el relato.', minutes: 'min', stops: 'paradas', finished: 'Recorrido completado', ask: 'Preguntar', routeUnavailable: 'La ruta o versión de idioma no está disponible. Elige otra ruta.', loadFailed: 'No se pudo cargar. Reintenta.', startFailed: 'No se pudo iniciar. Reintenta.', saveFailed: 'No se pudo guardar. Reintenta.', video: 'Ver vídeo', guide: 'Guía', noMap: 'Mapa no disponible. Puedes elegir rutas y escuchar relatos.', changeLanguage: 'Cambiar idioma', zoomIn: 'Acercar', zoomOut: 'Alejar', overview: 'Ver toda la ruta', follow: 'Vista de seguimiento', unfollow: 'Dejar de seguir', voiceAsk: 'Preguntar por voz', voiceStop: 'Detener', voiceHint: 'Toca y habla', voiceUnsupported: 'Este navegador no admite voz; cambiado a texto.' },
  fr: {
    chooseLanguage: 'Choisissez votre langue', routes: 'Choisissez votre parcours', routeHint: 'Chaque guide vous fait découvrir un autre visage de Pékin.', search: 'Rechercher un parcours, un guide ou une étape', start: 'Commencer le parcours', startHint: 'Activez la localisation pour écouter les récits en chemin', back: 'Retour à la carte', end: 'Terminer le parcours',
    play: 'Écouter le récit', pause: 'Pause', resume: 'Reprendre', content: 'Lire le récit', close: 'Fermer', next: 'À suivre', complete: 'Terminer cette étape', locate: 'Activer les récits à proximité', stopLocate: 'Désactiver la localisation', locationFailed: 'Localisation indisponible. Sélectionnez une étape manuellement.', loading: 'Chargement…', retry: 'Réessayer',
    noRoutes: 'Aucun parcours publié dans cette langue', noNarration: 'Aucun récit dans cette langue pour cette étape', voiceMissing: 'La voix de cette langue est indisponible. Vous pouvez lire le récit.', playbackFailed: 'Lecture impossible. Réessayez ou lisez le récit.', minutes: 'min', stops: 'étapes', finished: 'Parcours terminé', ask: 'Poser une question',
    routeUnavailable: 'Ce parcours ou sa version linguistique est indisponible. Choisissez un autre parcours.', loadFailed: 'Chargement impossible. Réessayez.', startFailed: 'Impossible de commencer. Réessayez.', saveFailed: 'Impossible de sauvegarder votre progression. Réessayez.', video: 'Voir la vidéo', guide: 'Guide', noMap: 'Carte indisponible. Vous pouvez choisir un parcours et écouter les récits.', changeLanguage: 'Changer de langue',
    zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', overview: 'Vue du parcours', follow: 'Suivre ma position', unfollow: 'Arrêter le suivi', voiceAsk: 'Poser une question à voix haute', voiceStop: 'Arrêter l’écoute', voiceHint: 'Appuyez et parlez', voiceUnsupported: 'Ce navigateur ne permet pas la saisie vocale. Saisissez votre question au clavier.',
  },
  ja: {
    chooseLanguage: 'ガイドの言語を選択', routes: 'コースを選択', routeHint: 'ガイドとともに、北京のさまざまな魅力を発見しましょう。', search: 'コース、ガイド、スポットを検索', start: 'コースを開始', startHint: '位置情報を有効にすると、道中でガイドを聞けます', back: '地図に戻る', end: 'コースを終了',
    play: 'ガイドを再生', pause: '一時停止', resume: '再開', content: '解説を読む', close: '閉じる', next: '次のスポット', complete: 'このスポットを完了', locate: '近くのスポットのガイドを有効にする', stopLocate: '位置情報を無効にする', locationFailed: '位置情報を取得できません。スポットを手動で選択してください。', loading: '読み込み中…', retry: '再試行',
    noRoutes: 'この言語で公開されているコースはありません', noNarration: 'このスポットにはこの言語の解説がありません', voiceMissing: 'この言語の音声が利用できません。解説をお読みください。', playbackFailed: '再生できません。再試行するか、解説をお読みください。', minutes: '分', stops: 'スポット', finished: 'コースを完了しました', ask: '質問する',
    routeUnavailable: 'このコースまたは言語版は利用できません。別のコースを選択してください。', loadFailed: '読み込めませんでした。再試行してください。', startFailed: '開始できませんでした。再試行してください。', saveFailed: '進行状況を保存できませんでした。再試行してください。', video: '動画を見る', guide: 'ガイド', noMap: '地図が利用できません。コースの選択とガイドの再生は可能です。', changeLanguage: '言語を変更',
    zoomIn: '拡大', zoomOut: '縮小', overview: 'コース全体を表示', follow: '現在地を追跡', unfollow: '追跡を終了', voiceAsk: '音声で質問', voiceStop: '音声入力を終了', voiceHint: 'タップして話してください', voiceUnsupported: 'このブラウザーは音声入力に対応していません。文字で質問してください。',
  },
}

export function tourMessages(locale: TourLocale): TourMessages { return { ...messages[locale], ...arrivalMessages[locale] } }
