<script setup lang="ts">
import { computed } from 'vue'
import { ClientSheet, ClientSheetContent, ClientSheetDescription, ClientSheetHeader, ClientSheetTitle } from '@/components/ui'
import type { RouteCardResponse } from '@/services/gameplay'

const props = defineProps<{ open: boolean; routes: RouteCardResponse[]; selectedRouteId: string; pending: boolean; error: string | null }>()
const emit = defineEmits<{ 'update:open': [value: boolean]; select: [routeId: string]; retry: [] }>()
const model = computed({ get: () => props.open, set: value => emit('update:open', value) })
</script>
<template><ClientSheet v-model="model"><ClientSheetContent side="bottom" class="route-picker"><ClientSheetHeader><ClientSheetTitle>选择游览路线</ClientSheetTitle><ClientSheetDescription>选择后，地图将显示已经审核发布的实际步行线路。</ClientSheetDescription></ClientSheetHeader><div class="route-list"><p v-if="pending" class="route-state">正在加载路线…</p><div v-else-if="error" class="route-state"><p>{{ error }}</p><button type="button" @click="$emit('retry')">重新加载</button></div><p v-else-if="!routes.length" class="route-state">当前地点暂无已发布路线</p><button v-for="route in routes" v-else :key="String(route.id)" type="button" class="route-option" :class="{ active: String(route.id) === selectedRouteId }" @click="$emit('select', String(route.id))"><div><span>{{ route.puzzleCount ?? 0 }} 站 · 约 {{ route.estimatedMinutes ?? 0 }} 分钟</span><h3>{{ route.title || '未命名路线' }}</h3><p>{{ route.theme || '沿途探索地点故事' }}</p></div><strong>{{ String(route.id) === selectedRouteId ? '当前' : '选择' }}</strong></button></div></ClientSheetContent></ClientSheet></template>
<style scoped>.route-picker{max-height:min(76vh,42rem);background:#17130e;color:#fff7e6}.route-list{display:grid;gap:.65rem;margin-top:1rem;overflow:auto;padding-bottom:calc(.75rem + env(safe-area-inset-bottom))}.route-option{display:flex;align-items:center;justify-content:space-between;gap:1rem;border:1px solid rgba(255,247,230,.12);border-radius:.85rem;background:rgba(255,247,230,.035);padding:.85rem;text-align:left}.route-option.active{border-color:rgba(226,183,99,.55);background:rgba(226,183,99,.08)}.route-option span{color:#d8ae63;font-size:.65rem}.route-option h3{margin:.2rem 0;color:#fff7e6;font-size:.92rem}.route-option p{margin:0;color:rgba(255,247,230,.55);font-size:.7rem}.route-option strong{color:#e7c37c;font-size:.72rem}.route-state{padding:2.5rem 1rem;text-align:center;color:rgba(255,247,230,.6)}.route-state button{margin-top:.6rem;color:#e7c37c}</style>
